### ISSUE TITLE
Upgrade fontconfig package

### ISSUE THREAD

**Issue by okcoker** [mojodna/heroku-buildpack-cairo#14]
So I've been in contact with Heroku support and some of the contributors of node-canvas about a fontconfig problem and I think the root of problem was this in this buildpack the whole time. 

There is an issue with version `2.11.93` of fontconfig that doesn't allow for custom font registration on the system and the bug was [fixed](https://github.com/behdad/fontconfig/blob/d05d083e9f87eb378b92e477d34a88061a572d86/README#L14) in `2.11.94`.

The whole discussion around this issue can be found [here](https://github.com/Automattic/node-canvas/pull/715) but it would be nice to get the package within this buildpack upgraded to at least `2.11.94`. I was going to submit a PR but it looks like the packages are hosted on your S3 bucket.

**Comment by mojodna** [comment]
Oops! Yeah, I totally haven't been keeping up on dependency versions (largely because I don't actively use this). I'm doing a bit of cleanup now, including removing support for the `cedar` stack and will update `fontconfig` as part of the process.

Thanks for the heads-up!

**Comment by okcoker** [comment]
Ah actually I just realized I was using https://github.com/mojodna/heroku-buildpack-cairo.git#pango

Does this update remove the need for the extra `#pango` on the end?

**Comment by okcoker** [comment]
Just saw #15. Testing now.

**Comment by mojodna** [comment]
`#pango` was equivalent to `master` (or absent) before. To test #15, you'll need to use `#v1.14.6` as the ref name. (I think you already figured this out.)

**Comment by okcoker** [comment]
Works great, thanks! https://node-canvas-fonts.herokuapp.com/
