### ISSUE TITLE
Error fetching

### ISSUE THREAD

**Issue by bsantosh909** [mojodna/heroku-buildpack-cairo#17]
I have set the stack to cedar-14
and also added this buildpack but then it gives me this error

 !     error fetching custom buildpack https://github.com/mojodna/heroku-buildpack-cario.git
 !     Push failed

**Comment by sethfitz** [comment]
Change the buildpack URL to https://github.com/mojodna/heroku-buildpack-cairo.git (cario → cairo)

**Comment by bsantosh909** [comment]
Getting this error now:
Package pangocairo was not found in the pkg-config search path.
@mojodna
