### ISSUE TITLE
No package 'pangocairo' found 

### ISSUE THREAD

**Issue by mrueegg** [mojodna/heroku-buildpack-cairo#5]
Hi,

I'm using your cairo buildpack together with phantomjs and nodejs buildpacks. Unfortunately, I get the following error on Heroku:

    Package pangocairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `pangocairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'pangocairo' found 

Note that I use node-canvas v1.2.1.

Any idea what is wrong here?

Thanks in advance,
Michael

**Comment by mojodna** [comment]
I don't think Pango is part of (my) standard build.  It's probably time to update the dependencies, so I'll add that into the mix.

**Comment by mrueegg** [comment]
That would be great. In the meantime, I could downgrade to an older node-canvas version. Which version can you recommend or you know is working with the buildpack?

**Comment by mojodna** [comment]
I'd guess 1.1.x, but I'm not sure.

**Comment by mojodna** [comment]
Are you using cedar-14 on Heroku?  Pango is leading me down a list of other dependencies (fontconfig, harfbuzz) that may not build on the cedar stack as easily.

**Comment by mojodna** [comment]
...while watching a cedar-14 image being configured, I noticed that pango is part of the base image.  You could override PKG_CONFIG_PATH to include `/usr/lib/pkgconfig` (I think) and possibly pick up Pango support w/o any dependency rebuilds.  The easiest way to do this is using `heroku bash`, setting `PKG_CONFIG_PATH`, and attempting to install node-canvas.

**Comment by mrueegg** [comment]
No, I'm still using cedar-10. Downgrading to node-canvas 1.1.6 helped me to get around this problem. As this version is fine for me, I'll stick with that for the moment. Thanks for your help!

**Comment by mojodna** [comment]
Great.  If/when you do decide you want/need to upgrade, try using cedar-14 and report back!
